version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ayurvedic-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ayurvedic_traceability
    volumes:
      - mongodb_data:/data/db
    networks:
      - ayurvedic-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ayurvedic-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/ayurvedic_traceability?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - ayurvedic-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ayurvedic-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - ayurvedic-network

volumes:
  mongodb_data:

networks:
  ayurvedic-network:
    driver: bridge
