#!/bin/bash
# Quick setup script for Gemini AI integration

echo "🌿 Setting up Gemini AI for Ayurvedic Herb Identification..."
echo ""
echo "Step 1: Get your Gemini API Key"
echo "- Visit: https://aistudio.google.com/"
echo "- Sign in with Google account"
echo "- Click 'Get API Key'"
echo "- Create new API key"
echo "- Copy the key"
echo ""
echo "Step 2: Update .env file"
echo "- Open backend/.env"
echo "- Replace 'your_gemini_api_key_here' with your actual key"
echo ""
echo "Step 3: Restart backend"
echo "- Stop current server (Ctrl+C)"
echo "- Run 'npm start' in backend folder"
echo ""
echo "🤖 Features of new AI integration:"
echo "✅ Real herb identification using Google Gemini AI"
echo "✅ Ayurvedic-specific training prompts"
echo "✅ Scientific and vernacular names"
echo "✅ Traditional uses and properties"
echo "✅ Enhanced confidence scoring"
echo "✅ Fallback system for reliability"
echo ""
echo "Ready to identify herbs with real AI! 🚀"
